[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Frame-Options = "SAMEORIGIN"

# Enforce HTTPS and www->root redirect logic OFF (handled in dashboard)
