[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Optional SPA fallback (not strictly needed here)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
