[build]
  publish = "."

# Limpia /admin vs /admin/
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# Sirve config.yml con MIME correcto y evita caché en admin
[[headers]]
  for = "/admin/config.yml"
  [headers.values]
  Content-Type = "text/yaml; charset=utf-8"

[[headers]]
  for = "/admin/*"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
