backend:
  name: git-gateway
  branch: main

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

collections:
  - name: "site"
    label: "Site / Sitio"
    files:
      - file: "content/site.json"
        label: "Main content / Contenido principal"
        name: "site"
        fields:
          - { label: "Title (EN)", name: "title_en", widget: "string" }
          - { label: "Subtitle (EN)", name: "subtitle_en", widget: "string" }
          - { label: "Title (ES)", name: "title_es", widget: "string" }
          - { label: "Subtitle (ES)", name: "subtitle_es", widget: "string" }
          - { label: "Instagram (handle or url)", name: "instagram", widget: "string" }
          - { label: "WhatsApp (full link)", name: "whatsapp", widget: "string" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string", required: false }
          - label: "Aftercare (EN)"
            name: "aftercare_en"
            widget: "list"
            fields:
              - { label: "Step", name: "step", widget: "text" }
          - label: "Aftercare (ES)"
            name: "aftercare_es"
            widget: "list"
            fields:
              - { label: "Paso", name: "step", widget: "text" }
