backend:
  name: git-gateway
  branch: main

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

publish_mode: simple

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "site"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Instagram", name: "instagram", widget: "string" }
          - { label: "WhatsApp", name: "whatsapp", widget: "string" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string", required: false }
