backend:
  name: git-gateway
  branch: main
  repo: carajo8a74-lang/Grimlayertattoos

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

collections:
  - name: "appointments"
    label: "Appointments"
    folder: "content/appointments"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tattoo Description", name: "description", widget: "text" }

  - name: "aftercare"
    label: "Aftercare"
    folder: "content/aftercare"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
