backend:
  name: git-gateway
  branch: main
  site_domain: grimlayertattoo.com
  identity_url: "https://grimlayertattoo.com/.netlify/identity"
  gateway_url: "https://grimlayertattoo.com/.netlify/git"

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

locale: en
