backend:
  name: git-gateway
  repo: carajo8a74-lang/Grimlayertattoos
  branch: main

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "site"
        fields:
          - { label: "Title (EN)", name: "title_en", widget: "string", default: "High-detail tattoos in Tampa" }
          - { label: "Subtitle (EN)", name: "subtitle_en", widget: "string", default: "Online booking and aftercare with protective film (Saniderm/Emalla)." }
          - { label: "Title (ES)", name: "title_es", widget: "string", default: "Tatuajes de alto detalle en Tampa" }
          - { label: "Subtitle (ES)", name: "subtitle_es", widget: "string", default: "Reserva online y aftercare con membrana protectora (Saniderm/Emalla)." }
          - { label: "Instagram", name: "instagram", widget: "string", default: "@grimlayertattoo" }
          - { label: "WhatsApp URL", name: "whatsapp", widget: "string", default: "https://wa.me/1xxxxxxxxxx" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string", required: false }
