backend:
  name: git-gateway
  branch: main

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

collections:
  - name: "site"
    label: "Site / Sitio"
    files:
      - file: "content/site.json"
        label: "Main content / Contenido principal"
        name: "site"
        fields:
          - { label: "Title (EN)", name: "en.title", widget: "string" }
          - { label: "Subtitle (EN)", name: "en.subtitle", widget: "string" }
          - { label: "Instagram (EN)", name: "en.instagram", widget: "string" }
          - { label: "WhatsApp (EN)", name: "en.whatsapp", widget: "string" }
          - label: "Gallery (EN)"
            name: "en.gallery"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string", required: false }
          - { label: "Aftercare (EN) — HTML allowed", name: "en.aftercare_html", widget: "text" }

          - { label: "Título (ES)", name: "es.title", widget: "string" }
          - { label: "Subtítulo (ES)", name: "es.subtitle", widget: "string" }
          - { label: "Instagram (ES)", name: "es.instagram", widget: "string" }
          - { label: "WhatsApp (ES)", name: "es.whatsapp", widget: "string" }
          - label: "Galería (ES)"
            name: "es.gallery"
            widget: "list"
            fields:
              - { label: "Imagen", name: "image", widget: "image" }
              - { label: "Alt", name: "alt", widget: "string", required: false }
          - { label: "Aftercare (ES) — HTML permitido", name: "es.aftercare_html", widget: "text" }
