backend:
  name: git-gateway
  branch: main
  repo: carajo8a74-lang/Grimlayertattoos

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "aftercare"
    label: "Aftercare"
    folder: "content/aftercare"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "booking"
    label: "Booking Info"
    folder: "content/booking"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Message", name: "body", widget: "markdown" }
