backend:
  name: git-gateway
  branch: main
  identity_url: https://grimlayertattoo.com/.netlify/identity
  gateway_url: https://grimlayertattoo.com/.netlify/git

site_url: https://grimlayertattoo.com
display_url: https://grimlayertattoo.com

media_folder: "assets/portfolio"
public_folder: "/assets/portfolio"

collections:
  - name: "site_en"
    label: "Homepage (EN)"
    file: "content/site.en.json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Aftercare (markdown)", name: "aftercare_md", widget: "markdown" }

  - name: "site_es"
    label: "Inicio (ES)"
    file: "content/site.es.json"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
      - label: "Galería"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Imagen", name: "image", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string", required: false }
      - { label: "Aftercare (markdown)", name: "aftercare_md", widget: "markdown" }
